Add pthread and dl to TARGET_LINK_LIBRARIES to fix linker errors:
Before:

Linking CXX executable sqliteman
/usr/bin/ld: sqlite/libsqlite_lib.a(sqlite3.c.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [sqliteman/sqliteman] Error 1
make[1]: *** [sqliteman/CMakeFiles/sqliteman.dir/all] Error 2
make: *** [all] Error 2

After adding pthread

Linking CXX executable sqliteman
/usr/bin/ld: sqlite/libsqlite_lib.a(sqlite3.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [sqliteman/sqliteman] Error 1
make[1]: *** [sqliteman/CMakeFiles/sqliteman.dir/all] Error 2
make: *** [all] Error 2

After adding dl

Linking CXX executable sqliteman
[ 94%] Built target sqliteman
[ 95%] Built target sqlitecompress
[ 95%] Built target sqlitedummy
[ 96%] Built target sqlitefunctions
[ 97%] Built target sqliteipv4
[ 98%] Built target sqlitemd5
[ 99%] Built target sqlitertree
[100%] Built target sqlitetablepopulation